CREATE SCHEMA BRH;

USE BRH;

create table ATRIBUICAO (
COLABORADOR INT NOT NULL,
PROJETO int NOT NULL,
PAPEL int   NOT NULL
);    



create table ENDERECO (
logradouro VARCHAR (200) not null,
bairro  VARCHAR(50) not NUll,
cidade  VARCHAR(100) not null,
estado  VARCHAR(2)not NULL,
complemento VARCHAR (50) not null,
cep  INT   not null
);



create table COLABORADOR (
MATRICULA_COLABORADOR INT NOT NULL,
departamento VARCHAR (50) not null,
CPF VARCHAR (100) NOT NULL,
NOME VARCHAR    (100) NOT NULL,
SALARIO INT NULL,
PRIMARY KEY (MATRICULA_COLABORADOR)
);



create table DEPARTAMENTO (
SIGLA 	VARCHAR (50) NOT NULL,
departamento_superior VARCHAR (50) not null,
NOME VARCHAR (100) NOT NULL,
CHEFE INT NOT NULL,
PRIMARY KEY (SIGLA)
);



create table PAPEL (
ID_PAPEL INT NOT NULL,
NOME VARCHAR (100) NOT NULL,
PRIMARY KEY (ID_PAPEL));



create table DEPENDENTE (
CPF INT NOT NULL,
NOME VARCHAR (100) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
PARENTESCO VARCHAR (50) NOT NULL,
colaborador VARCHAR (100) NOT NULL,
PRIMARY KEY (CPF));



create table PROJETO (
ID_PROJETO INT NOT NULL,
NOME VARCHAR (100) NOT NULL,
RESPONSAVEL VARCHAR    (100) NOT NULL,
DATA_INICIO DATE NOT NULL,
dATA_FINAL DATE NOT NULL,
PRIMARY KEY (ID_PROJETO));



create table CONTATO (
MATRICULA_COLABORADOR INT NOT NULL,
TELEFONE_1 INT NOT NULL,
TELEFONE_2 INT ,
EMAIL_PESSOAL VARCHAR (100) NOT NULL,
EMAIL_CORPORATIVO VARCHAR (100) NOT NULL,
PRIMARY KEY (MATRICULA_COLABORADOR));







ALTER TABLE ATRIBUICAO ADD CONSTRAINT FK_COLABORADOR
FOREIGN KEY (COLABORADOR)
REFERENCES COLABORADOR (MATRICULA_COLABORADOR);



ALTER TABLE COLABORADOR ADD CONSTRAINT PK_COLABORADOR_DEPARTAMENTO
FOREIGN KEY (departamento)
REFERENCES DEPARTAMENTO (sigla);



ALTER TABLE DEPARTAMENTO ADD CONSTRAINT FK_CHEFE_DEPARTAMENTO
FOREIGN KEY (CHEFE)
REFERENCES COLABORADOR (MATRICULA_COLABORADOR);



ALTER TABLE ENDERECO ADD CONSTRAINT FK_COLABORADOR_ENDERECO
FOREIGN KEY (CEP)
REFERENCES COLABORADOR (MATRICULA_COLABORADOR);



ALTER TABLE CONTATO ADD CONSTRAINT FK_COLABORADOR_CONTATO
FOREIGN KEY (MATRICULA_COLABORADOR)
REFERENCES COLABORADOR (MATRICULA_COLABORADOR);



ALTER TABLE PROJETO ADD CONSTRAINT FK_RESPONSAVEL
FOREIGN KEY (ID_PROJETO)
REFERENCES COLABORADOR (MATRICULA_COLABORADOR);



ALTER TABLE ATRIBUICAO ADD CONSTRAINT FK_PAPEL
FOREIGN KEY (PAPEL)
REFERENCES PAPEL (ID_PAPEL);



ALTER TABLE ATRIBUICAO ADD CONSTRAINT FK_PROJETO
FOREIGN KEY (PROJETO)
REFERENCES PROJETO (ID_PROJETO);